name: teste
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.0.0
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  mobx_codegen: ^2.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
