// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1yXPhf0pc1rm5vODmM7dwM9nYt7yivA',
    appId: '1:626505792329:web:2c4eca075007dc613cb898',
    messagingSenderId: '626505792329',
    projectId: 'teste-3219a',
    authDomain: 'teste-3219a.firebaseapp.com',
    databaseURL: 'https://teste-3219a-default-rtdb.firebaseio.com',
    storageBucket: 'teste-3219a.appspot.com',
    measurementId: 'G-8FWDJE9693',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoY7JCGdi-3THlIdzYm3mkQrJ0eeXTtqs',
    appId: '1:626505792329:android:1cb41e43a84c75423cb898',
    messagingSenderId: '626505792329',
    projectId: 'teste-3219a',
    databaseURL: 'https://teste-3219a-default-rtdb.firebaseio.com',
    storageBucket: 'teste-3219a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIzwoGyHj86io0mS52toev6BnDrF68T9o',
    appId: '1:626505792329:ios:9b8b0bd917a6427c3cb898',
    messagingSenderId: '626505792329',
    projectId: 'teste-3219a',
    databaseURL: 'https://teste-3219a-default-rtdb.firebaseio.com',
    storageBucket: 'teste-3219a.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIzwoGyHj86io0mS52toev6BnDrF68T9o',
    appId: '1:626505792329:ios:9b8b0bd917a6427c3cb898',
    messagingSenderId: '626505792329',
    projectId: 'teste-3219a',
    databaseURL: 'https://teste-3219a-default-rtdb.firebaseio.com',
    storageBucket: 'teste-3219a.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd1yXPhf0pc1rm5vODmM7dwM9nYt7yivA',
    appId: '1:626505792329:web:1798ea85d1c5e4833cb898',
    messagingSenderId: '626505792329',
    projectId: 'teste-3219a',
    authDomain: 'teste-3219a.firebaseapp.com',
    databaseURL: 'https://teste-3219a-default-rtdb.firebaseio.com',
    storageBucket: 'teste-3219a.appspot.com',
    measurementId: 'G-1Y0HHNXR17',
  );
}
